import type { AnalysisReport, DebateResult, KnowledgeGraph, NormalizedDocument } from "../types/api";

export const documentFixture: NormalizedDocument = {
  document_id: "doc_test-123",
  filename: "strategy.pdf",
  file_type: "pdf",
  status: "processed",
  content: [
    { type: "page", location: 1, text: "Market context", extra: {} },
    { type: "page", location: 2, text: "Revenue depends on one customer.", extra: {} },
  ],
  metadata: { page_count: 2 },
  warnings: [],
};

export const visualDocumentFixture: NormalizedDocument = {
  document_id: "doc_visual-123",
  filename: "strategy-chart.png",
  file_type: "image",
  status: "processed",
  content: [{
    type: "image",
    location: 1,
    text: "Visual summary:\nRevenue rises while operating margin falls.",
    extra: { visual_analysis: true, visual_source: "multimodal" },
  }],
  metadata: {
    width: 1200,
    height: 800,
    multimodal: {
      status: "completed",
      provider: "test-provider",
      model: "test-vision",
      attempted: 1,
      succeeded: 1,
      failed: 0,
    },
  },
  warnings: [],
};

export const analysisFixture: AnalysisReport = {
  document_id: documentFixture.document_id,
  status: "completed",
  summary: "The strategy has a promising market but concentrated revenue exposure.",
  overall_assessment: "Validate demand and diversify before scaling.",
  risks: [{
    title: "Customer concentration",
    description: "One customer accounts for most planned revenue.",
    severity: "high",
    evidence: "Revenue depends on one customer.",
    source_locations: [2],
    recommendation: "Build a diversified pipeline.",
  }],
  assumptions: [{
    title: "Demand remains stable",
    description: "The plan assumes stable demand.",
    confidence: "medium",
    evidence: "Market context",
    source_locations: [1],
    why_it_matters: "Demand drives the forecast.",
  }],
  biases: [],
  missing_perspectives: [{
    perspective: "Customer operations",
    description: "Operational buyers were not represented.",
    why_it_matters: "They own adoption.",
    questions_to_consider: ["Who will operate the product?"],
  }],
  unanswered_questions: [{ question: "What is the fallback plan?", importance: "high", reason: "Resilience is unclear." }],
  recommendations: [{ priority: "high", title: "Diversify demand", description: "Secure three independent pilots." }],
  metadata: { rag_enabled: true, model: "test-model" },
};

export const debateFixture: DebateResult = {
  document_id: documentFixture.document_id,
  status: "completed",
  agent_analyses: [{
    agent: "skeptic",
    role: "Challenges weak claims",
    status: "succeeded",
    error: null,
    summary: "The growth case is under-evidenced.",
    findings: [{
      title: "Unvalidated growth",
      description: "The forecast lacks independent validation.",
      severity: "high",
      evidence: "Revenue depends on one customer.",
      source_locations: [2],
      recommendation: "Test the forecast.",
    }],
    assumptions: [],
    questions: [],
    confidence: "high",
    metadata: {},
  }],
  agreements: ["Demand validation is essential."],
  disagreements: ["The panel differs on timing."],
  final_blind_spots: ["No downside scenario."],
  final_risks: analysisFixture.risks,
  final_assumptions: analysisFixture.assumptions,
  final_biases: [],
  missing_perspectives: analysisFixture.missing_perspectives,
  unanswered_questions: analysisFixture.unanswered_questions,
  recommendations: analysisFixture.recommendations,
  overall_assessment: "Proceed only after validating the core assumptions.",
  metadata: { successful_agents: ["skeptic"], rag_enabled: true },
};

export const graphFixture: KnowledgeGraph = {
  document_id: documentFixture.document_id,
  scope: "document",
  version_group_id: null,
  nodes: [
    {
      id: "gn_11111111111111111111111111111111",
      type: "document",
      label: "strategy.pdf",
      description: "Current document",
      document_ids: [documentFixture.document_id],
      origins: ["deterministic"],
      metadata: { file_type: "pdf" },
    },
    {
      id: "gn_22222222222222222222222222222222",
      type: "risk",
      label: "Customer concentration",
      description: "One customer accounts for most planned revenue.",
      document_ids: [documentFixture.document_id],
      origins: ["analysis"],
      metadata: { severity: "high" },
    },
    {
      id: "gn_33333333333333333333333333333333",
      type: "recommendation",
      label: "Build a diversified pipeline",
      description: "Reduce dependency on a single customer.",
      document_ids: [documentFixture.document_id],
      origins: ["analysis"],
      metadata: { priority: "high" },
    },
    {
      id: "gn_44444444444444444444444444444444",
      type: "evidence",
      label: "Revenue depends on one customer",
      description: "Revenue depends on one customer.",
      document_ids: [documentFixture.document_id],
      origins: ["analysis"],
      metadata: { source_locations: [2], visual_derived: false },
    },
    {
      id: "gn_55555555555555555555555555555555",
      type: "source",
      label: "Page 2",
      description: "Revenue depends on one customer.",
      document_ids: [documentFixture.document_id],
      origins: ["analysis"],
      metadata: { source_type: "page", source_location: 2, version_number: null },
    },
  ],
  edges: [
    {
      id: "ge_11111111111111111111111111111111",
      source: "gn_11111111111111111111111111111111",
      target: "gn_22222222222222222222222222222222",
      type: "contains",
      origin: "deterministic",
      metadata: {},
    },
    {
      id: "ge_22222222222222222222222222222222",
      source: "gn_22222222222222222222222222222222",
      target: "gn_33333333333333333333333333333333",
      type: "addressed_by",
      origin: "analysis",
      metadata: {},
    },
    {
      id: "ge_33333333333333333333333333333333",
      source: "gn_44444444444444444444444444444444",
      target: "gn_22222222222222222222222222222222",
      type: "supports",
      origin: "analysis",
      metadata: {},
    },
    {
      id: "ge_44444444444444444444444444444444",
      source: "gn_44444444444444444444444444444444",
      target: "gn_55555555555555555555555555555555",
      type: "has_source",
      origin: "analysis",
      metadata: {},
    },
  ],
  diagnostics: [{
    type: "orphan_risk",
    node_id: "gn_22222222222222222222222222222222",
    title: "Risk lacks grounded evidence",
    description: "No validated evidence supports this risk.",
    severity: "warning",
  }],
  truncated: false,
  metadata: { node_count: 5, edge_count: 4 },
};
